feat(tokens): adds support for creating tokens to the sdk
evervault/evervault-php pull request #9
Opened 2023-08-09 14:48 UTC by jakekgrog

# Why
Need to support the creation of tokens in the PHP SDK

# How
- Add `createClientSideDecryptToken()` to allow

2023-08-10 13:44 UTC, jeremywagemans commented on README.md
> +### $evervault->decrypt()
this section is duplicated!

2023-08-10 13:48 UTC, jakekgrog commented on README.md
> +### $evervault->decrypt()
how'd that get there lol

2023-08-10 13:49 UTC, jeremywagemans commented on src/Evervault/EvervaultHttp.php
> +        $response = $this->_makeCreateTokenRequest($payload);
This is not needed. You can just rely on `_makeApiRequest`, similary to how it's done in `decrypt`

2023-08-10 13:53 UTC, jeremywagemans commented on README.md
> +If the `$data` parameter is provided, the token can only be used to decrypt that specific payload. Otherwise, the token can be used to decrypt any payload.
for decrypt, it is actually required to pass the payload :)

2023-08-10 13:54 UTC, jeremywagemans requested changes
Added a few comments!

2023-08-14 08:52 UTC, jeremywagemans commented on src/Evervault/EvervaultHttp.php
> +    private function _makeCreateTokenRequest($payload, $headers=[]) {
Remove this

2023-08-14 08:52 UTC, jeremywagemans commented on src/Evervault/EvervaultHttp.php
> +    private function _makeDecryptRequest($data, $headers=[]) {
Remove this

2023-08-14 10:05 UTC, jeremywagemans commented on src/Evervault/Evervault.php
> +            throw new EvervaultError('Please provide a payload');
Can you improve this error message to make it more user friendly?

```suggestion
            throw new EvervaultError('The `$data` parameter is required and ensures the issued token can only be used to decrypt that specific payload.');
```

2023-08-14 10:08 UTC, jeremywagemans commented on src/Evervault/EvervaultHttp.php
> +        $response = $this->_makeApiRequest('POST', $this->$createTokenPath, $payload, [], true);
This doesn't work:

```suggestion
        $response = $this->_makeApiRequest('POST', $this->createTokenPath, $payload, [], true);
```

2023-08-14 10:09 UTC, jeremywagemans commented on src/Evervault/Evervault.php
> +        return $this->httpClient->createToken("api:decrypt", $data, $expiry);
The grant is invalid:

```suggestion
        return $this->httpClient->createToken("decrypt:api", $data, $expiry);
```

2023-08-14 10:19 UTC, jeremywagemans commented on src/Evervault/Evervault.php
> +    public function createClientSideDecryptToken($data, $expiry) {
We should make this parameter optional

```suggestion
    public function createClientSideDecryptToken($data, $expiry = null) {
```

2023-08-14 10:19 UTC, jeremywagemans requested changes
Some implementation issues

2023-08-14 14:58 UTC, jeremywagemans commented on src/Evervault/EvervaultHttp.php
> +        } else if ($responseCode !== 200 || $responseCode !== 201) {
This should be `responseCode !== 200 && $responseCode !== 201`.

2023-08-14 16:16 UTC, jeremywagemans requested changes
Looks good except one last issue!

2023-08-15 09:48 UTC, jeremywagemans approved these changes
lgtm!

2023-08-23 10:16 UTC, merged